// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIF4c1o7fWd4lstnc25BKGd7rMSAzCvQw',
    appId: '1:677639505231:web:f436db1d247879d8b7313a',
    messagingSenderId: '677639505231',
    projectId: 'awesome-focus',
    authDomain: 'awesome-focus.firebaseapp.com',
    storageBucket: 'awesome-focus.appspot.com',
    measurementId: 'G-BKLRGWJWQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw26PFUjBc3-ZXnGdZ7FLkxPZONqFaoX0',
    appId: '1:677639505231:android:7f15db131d1b62a7b7313a',
    messagingSenderId: '677639505231',
    projectId: 'awesome-focus',
    storageBucket: 'awesome-focus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1jemQzBKvkYZ9PCljPuio8yUqGrz9rbM',
    appId: '1:677639505231:ios:d8d27f34e0e4cac4b7313a',
    messagingSenderId: '677639505231',
    projectId: 'awesome-focus',
    storageBucket: 'awesome-focus.appspot.com',
    iosClientId: '677639505231-ioudipgk7kj9hs7htlif64k27rq7mips.apps.googleusercontent.com',
    iosBundleId: 'com.example.heatMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1jemQzBKvkYZ9PCljPuio8yUqGrz9rbM',
    appId: '1:677639505231:ios:d8d27f34e0e4cac4b7313a',
    messagingSenderId: '677639505231',
    projectId: 'awesome-focus',
    storageBucket: 'awesome-focus.appspot.com',
    iosClientId: '677639505231-ioudipgk7kj9hs7htlif64k27rq7mips.apps.googleusercontent.com',
    iosBundleId: 'com.example.heatMapApp',
  );
}
